
package com.sap.xi.a1s.global;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManageMarketingLeadIn", targetNamespace = "http://sap.com/xi/A1S/Global")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sap.xi.a1s.global.ObjectFactory.class,
    com.sap.xi.ap.common.gdt.ObjectFactory.class,
    com.sap.xi.ap.common.global.ObjectFactory.class,
    com.sap.xi.ap.crm.global.ObjectFactory.class,
    com.sap.xi.basis.global.ObjectFactory.class,
    com.sap.xi.documentservices.global.ObjectFactory.class,
    com.sap.xi.sapglobal20.global.ObjectFactory.class
})
public interface ManageMarketingLeadIn {


    /**
     * 
     * @param marketingLeadBundleMaintainRequestSync
     * @return
     *     returns com.sap.xi.a1s.global.MarketingLeadMaintainConfirmationBundleMessageSync
     * @throws StandardFaultMessage
     */
    @WebMethod(operationName = "MaintainBundle", action = "http://sap.com/xi/A1S/Global/ManageMarketingLeadIn/MaintainBundleRequest")
    @WebResult(name = "MarketingLeadBundleMaintainConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MarketingLeadBundleMaintainConfirmation_sync")
    public MarketingLeadMaintainConfirmationBundleMessageSync maintainBundle(
        @WebParam(name = "MarketingLeadBundleMaintainRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MarketingLeadBundleMaintainRequest_sync")
        MarketingLeadMaintainRequestBundleMessageSync marketingLeadBundleMaintainRequestSync)
        throws StandardFaultMessage
    ;

    /**
     * 
     * @param marketeingLeadRequestBundleCheckMaintainQuerySync
     * @return
     *     returns com.sap.xi.a1s.global.MarketingLeadMaintainConfirmationBundleMessageSync
     * @throws StandardFaultMessage
     */
    @WebMethod(operationName = "CheckMaintainBundle", action = "http://sap.com/xi/A1S/Global/ManageMarketingLeadIn/CheckMaintainBundleRequest")
    @WebResult(name = "MarketingLeadRequestBundleCheckMaintainResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MarketingLeadRequestBundleCheckMaintainResponse_sync")
    public MarketingLeadMaintainConfirmationBundleMessageSync checkMaintainBundle(
        @WebParam(name = "MarketeingLeadRequestBundleCheckMaintainQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "MarketeingLeadRequestBundleCheckMaintainQuery_sync")
        MarketingLeadMaintainRequestBundleMessageSync marketeingLeadRequestBundleCheckMaintainQuerySync)
        throws StandardFaultMessage
    ;

}
