
package com.sap.xi.a1s.global;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "StandardFaultMessage", targetNamespace = "http://sap.com/xi/AP/Common/Global")
public class StandardFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.sap.xi.ap.common.global.StandardFaultMessage faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public StandardFaultMessage(String message, com.sap.xi.ap.common.global.StandardFaultMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public StandardFaultMessage(String message, com.sap.xi.ap.common.global.StandardFaultMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sap.xi.ap.common.global.StandardFaultMessage
     */
    public com.sap.xi.ap.common.global.StandardFaultMessage getFaultInfo() {
        return faultInfo;
    }

}
